### ISSUE TITLE
Cant Resolve Reboot

### ISSUE THREAD

**Issue by idkjs** [jsiebern/bs-material-ui#1]
Running the example files is getting me this result.

```
Failed to compile.

./node_modules/@jsiebern/bs-material-ui/lib/js/src/MaterialUi.bs.js
Module not found: Can't resolve 'material-ui/Reboot/Reboot' in '/Users/prisc_000/code/BHYV/bhyv-mui/node_modules/@jsiebern/bs-material-ui/lib/js/src'
```
This the bsconfig.json: https://github.com/idkjs/bs-mui-example/blob/master/bsconfig.json
This is package.json: https://github.com/idkjs/bs-mui-example/blob/master/package.json

**Comment by idkjs** [comment]
I've added material-ui to package.json.

now getting this error:

```
./node_modules/@jsiebern/bs-material-ui/lib/js/src/MaterialUi.bs.js
Module not found: Can't resolve 'material-ui/BottomNavigation/BottomNavigationAction' in '/Users/prisc_000/code/BHYV/bs-mui-example/node_modules/@jsiebern/bs-material-ui/lib/js/src'
```

**Comment by jsiebern** [comment]
Hey, yes, there was a recent Update in Mui that changed a few packages around. They announced some more breaking changes in the coming weeks until the final v1 release. I've updated the package, please upgrade and it should be fine!

**Comment by idkjs** [comment]
That worked. Will keep an eye for changes. So seems like should be possible generate the css from a theme.json file (compositor.io) and this tool, no?

**Comment by jsiebern** [comment]
Sorry, I can't answer that as I've never worked with that service!
