### ISSUE TITLE
TypographyStyleOptions

### ISSUE THREAD

**Issue by leeor** [jsiebern/bs-material-ui#100]
After updating to `1.3.0` I can no longer customize the font style of different UI variants (e.g., `body1`, `h1`, `h2`). The updated `TypographyStyleOptions` only has the option to specify a `fontFace` as a JSON object, with no helpers. This was the previous `TypographyStyleOptions`:

https://github.com/jsiebern/bs-material-ui/blame/2c9a9a4b7e38be879b911351ace9411bcd2b4bb6/public/bs-material-ui/src/MaterialUi_ThemeOptions.re#L2931-L2953

I had to resort to a workaround with `Obj.magic` and this fake `TypographyStyleOptions` module to be able to maintain the theme I'm using.

```reason
module TypographyStyleOptions = {
  let make = (~fontFamily, ~fontWeight=?, ()) => {
    Encode.object_(
      [
        ("font-family", Encode.string(fontFamily))->Some,
        fontWeight->Option.map(weight =>
          ("font-weight", Encode.string(weight))
        ),
      ]
      ->List.keepMap(Utils.identity),
    );
  };
};
```

```diff
         ThemeOptions.Typography.make(
           ~fontFamily="'Inter', sans-serif",
           ~h1=
-            ThemeOptions.TypographyStyleOptions.make(
+            TypographyStyleOptions.make(
               ~fontWeight="600",
               ~fontFamily="'Inter', sans-serif",
               (),
-            ),
+            )
+            ->Obj.magic,
```

Is this intentional and I missed the correct way of customizing the theme typography?

**Comment by jsiebern** [comment]
Intentional is always relative with these generated bindings 😉 They must have changed something over at the main repo, that prevents these options from being detected. I'll do some investigating on this.

**Comment by jsiebern** [comment]
It's still not extracting correctly. This is the JSON I get back for this entry (it depends on a third party typescript parse-tool, so unfortunately there's nothing I can do if it gives up on that particular type node):
```json
"TypographyStyleOptions": {
    "properties": {
        "@font-face": {
        }
    },
    "type": "object"
}
```

I'm working on my own typescript to reason solution atm to address specifically this problem. Until that's ready this type will probably have to stay this way.
