### ISSUE TITLE
disableShrink prop in CircularProgress component is missing

### ISSUE THREAD

**Issue by ansiwen** [jsiebern/bs-material-ui#102]
The origninal component has a boolean `disableShrink` prop, it doesn't appear in the binding code though:
https://github.com/jsiebern/bs-material-ui/blob/4ceab30b4e63e6ca639c9cc5ad3a9a1adf52a970/public/bs-material-ui/src/MaterialUi_CircularProgress.re#L82-L95

**Comment by jsiebern** [comment]
Will be included in the upcoming version, thanks for reporting 👍🏻
