### ISSUE TITLE
The PPX nightmare continues...

### ISSUE THREAD

**Issue by matzero** [jsiebern/bs-material-ui#105]
Of course the examples on this project do not include the configuration files so we are left to guess which combination of npm versions work together. 
These are my test results so far:

### On Mac->
package.json file with: 

"@jsiebern/bs-material-ui": "1.2.0",
"@jsiebern/bs-material-ui-ppx": "1.0.5"

OR 

"@jsiebern/bs-material-ui": "1.3.0-zero.2",
"@jsiebern/bs-material-ui-ppx": "1.1.0-zero.2",

OR

"@jsiebern/bs-material-ui": "1.3.0-zero.4",
"@jsiebern/bs-material-ui-ppx": "1.1.0-zero.4",

bsconfig.json:

  "ppx-flags": ["./node_modules/@jsiebern/bs-material-ui-ppx/ppx"],

**Results**: Fails with `Fatal error: exception Failure("Ast_mapper: OCaml version mismatch or malformed input")`

The only way you can get this to work is changing the ppx flag to use ppx6:

"ppx-flags": ["./node_modules/@jsiebern/bs-material-ui-ppx/ppx6"],

### On Linux Alpine ->

No combination of packages and ppx or ppx6 flags for the bsconfig.json seems to work.

### On Linux Ubuntu ->

Any combination of 

"@jsiebern/bs-material-ui": "1.3.0-zero.2",
"@jsiebern/bs-material-ui-ppx": "1.1.0-zero.2",

Works ONLY if you use ppx in the flags: 

"ppx-flags": ["./node_modules/@jsiebern/bs-material-ui-ppx/ppx"],

It fails if you use ppx6.

What am I doing wrong?

**Comment by matzero** [comment]
Resolution: 

After much more testing it seems that the only PPX package that works across ALL platforms with (bsconfig.json):

`"ppx-flags": ["./node_modules/@jsiebern/bs-material-ui-ppx/ppx"],`

It is this version (package.json):

"@jsiebern/bs-material-ui-ppx": "1.1.0-test.2"

Notice there is no ^ on the version number.

This works even in AlpineLinux.

Now for some reason in Ubuntu it also works with the ^ version modification but if you want to fix your CI just use the package above.

I will leave this open because I think the author should promote this version to be the default on the npm/yarn install.

**Comment by jsiebern** [comment]
Sorry about all the confusion, I'll take some time to get an update out soon. I'll deprecate the old API then and will clean up that version mess of the PPX 👍

**Comment by jsiebern** [comment]
This issue should be adressed with the latest package releases 😃
