### ISSUE TITLE
Collapse is missing mountOnEnter / unmountOnExit props

### ISSUE THREAD

**Issue by ansiwen** [jsiebern/bs-material-ui#106]
The Collapse component is missing at least the mountOnEnter / unmountOnExit props, that should be inherited from the Transition component.

**Comment by jsiebern** [comment]
Thanks for reporting, I'll put out an update this weekend probably.

**Comment by jsiebern** [comment]
Will be included in the upcoming version, thanks for reporting 👍🏻
