### ISSUE TITLE
Extra props to modal should be provided to the root component. 

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [jsiebern/bs-material-ui#110]
https://material-ui.com/api/modal/ In the last section it mentions `Any other props supplied will be provided to the root element (native element).` 

eg: providing className prop would apply it to the root element. With the current bindings, it is not possible to provide a className prop.

**Comment by jsiebern** [comment]
That is a problem I don't want to solve on the bindings level, sorry! There is a way to extend components like this if you absolutely need it:

```reason
module CircularProgressAria = {
  let makeProps = MaterialUi.CircularProgress.makeProps;
  let make = props => {
    React.cloneElement(
      <MaterialUi.CircularProgress />,
      Js.Obj.assign(props, {"aria-something": "something"}),
    );
  };
};
let component = <CircularProgressAria className="some-class" />;
```

It's not ideal but I want the bindings to keep close to the extraction definition, otherwise the maintenance of the bindings becomes too complex.
