### ISSUE TITLE
 bs-material-ui-lab@1.3.0-zero.3 depends on bs-material-ui@1.3.0-zero.1

### ISSUE THREAD

**Issue by Schmavery** [jsiebern/bs-material-ui#111]
First off, this package is a lifesaver, thanks a bunch for keeping it running.

I recently wanted to use some components from the labs package, and noticed that it resulted in multiple versions of bs-material-ui getting installed and some warnings.

```
Duplicated package: @jsiebern/bs-material-ui /Users/avery/git/tessel/tesselapp/seating/node_modules/@jsiebern/bs-material-ui (chosen) vs /Users/avery/git/tessel/tesselapp/seating/node_modules/@jsiebern/bs-material-ui-lab/node_modules/@jsiebern/bs-material-ui in /Users/avery/git/tessel/tesselapp/seating/node_modules/@jsiebern/bs-material-ui-lab
```

Everything seems to be working alright so far but it was slightly worry-inducing so I thought I'd point it out in case it was a little mistake. Not a huge deal, thanks again!

**Comment by jsiebern** [comment]
Thanks for the praise, it's much appreciated. I'm really glad you find it useful.
It probably is a mistake of some sort, the current packages are a mess unfortunately. I'm working towards cleaning this up and providing some documentation as well, won't be too much longer.

The zero branches will be the main package and I'll have them all running together (incl. ppx) nicely as a priority.

**Comment by jsiebern** [comment]
This issue should be adressed with the latest package releases 😃
