### ISSUE TITLE
Binding for CircularProgressWithLabel

### ISSUE THREAD

**Issue by searleser97** [jsiebern/bs-material-ui#112]
Binding for CircularProgressWithLabel seems to be missing

[https://material-ui.com/components/progress/#circular-with-label](https://material-ui.com/components/progress/#circular-with-label)

**Comment by jsiebern** [comment]
Looks to me like that is just a demo component. If you look at the source, you'll see that they construct it manually from the normal `CircularProgress`. 

Also  not listed here: https://github.com/mui-org/material-ui/tree/next/packages/material-ui/src .
So I'll go with demo :)

**Comment by searleser97** [comment]
You are right, thanks
