### ISSUE TITLE
How can I annotate the classes record from useStyles hook?

### ISSUE THREAD

**Issue by studious** [jsiebern/bs-material-ui#113]
My project has a few functions that take the classes record as a parameter and since moving to the makeStyles notation and useStyles hook I am getting errors about record field not found.

How can I type this given the record is generated by the ppx?

Thanks

**Comment by studious** [comment]
I think I might have finally spotted something in your tests that helped.

module MyStyle = [%makeStyles({....})];

`MyStyle.classes` seems to do the trick.

**Comment by jsiebern** [comment]
Glad you've solved it. Let me know if you need further help with this 😃
