### ISSUE TITLE
Issue accessing fontSize on typography

### ISSUE THREAD

**Issue by bdunn313** [jsiebern/bs-material-ui#116]
This is likely because of a misunderstanding of how to do this properly, but I was trying to write up a makeStyles and utilize a fontSize off of my generated theme instead of hardcoding a value. The best I could do was use a magic object via a custom `getFontSize` helper:

```re
let getFontSize = (style) => Obj.magic(style)##fontSize;
let menuLabelStyles = (theme: MaterialUi.Theme.t) => ReactDOMRe.Style.make(~fontSize=getFontSize(theme.typography.subtitle1), ());
```

Is there a better way to achieve the above?

**Comment by bdunn313** [comment]
The above doesn't really appear to work properly, but the question still stands: How do I access theme.typography font size info?

**Comment by jsiebern** [comment]
@bdunn313 No, you're doing it right. Sorry, the theme type detection is very spotty and not a trivial problem to extract from typescript. I'm still working on that problem, but it'll probably be a while still. You're approach is the right one for the time being.
