### ISSUE TITLE
Add my project under the Example section of README?

### ISSUE THREAD

**Issue by feihong** [jsiebern/bs-material-ui#12]
Hi, I created a small app using your bindings and it worked great! You can find it at https://github.com/feihong/cool-char-generator. Although it's a full-fledged program, it's pretty small so I think it works as example code. If you like, you could add a link to it under the Example section of README.md. 

The code shows usage of Button, Grid, FormControl, Select, MenuItem, and Popover components. I think the most useful part is [how it deals with the anchorEl argument of the Popover component](https://github.com/feihong/cool-char-generator/blob/glitch/src/CoolCharGenerator.re#L87). This was the only thing that I really struggled with when using your bindings, probably because I'm relatively new to Reason.

If you prefer, I can make the edits to README.md myself and send you a PR.

**Comment by jsiebern** [comment]
@feihong Not sure I want the whole project as an example but if you want to send a PR for the examples folder that deals with the achorEl thing (and you are welcome to link your the project in that file as a comment), I'd gladly accept that PR :)

**Comment by jsiebern** [comment]
Awesome @feihong , thank you!
