### ISSUE TITLE
Rescript incompatibility

### ISSUE THREAD

**Issue by montogeek** [jsiebern/bs-material-ui#120]
Hi!

I just installed these bindings in a Rescript project, unfortunately I am getting the following error:

```bash
  It's possible that your build is stale.
  Try to clean the artifacts and build again?

  Here's the original error message
  The files /Users/fernando/Code/rescript/node_modules/@jsiebern/bs-material-ui/lib/ocaml/materialUi.cmi
  and /Users/fernando/Code/rescript/node_modules/@rescript/react/lib/ocaml/react.cmi
  make inconsistent assumptions over interface React

FAILED: cannot make progress due to previous errors.
>>>> Finish compiling(exit: 1)
```

My code:
```res
// Main.res
@react.component
let make = () => {
  open MaterialUi
  <Container>
    {React.string("Hello World")}
  </Container> 
}
```

package.json
```json
{
  "scripts": {
    "re:build": "bsb -make-world -clean-world",
    "re:watch": "bsb -make-world -clean-world -w"
  },
  "dependencies": {
    "@jsiebern/bs-material-ui": "2.0.2",
    "@material-ui/core": "4.11.3",
    "@rescript/react": "0.10.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "reason-react": "^0.9.1",
    "snowpack": "3.0.11"
  }
}
```

bsconfig.json
```json
{
  "name": "rescript",
  "reason": { "react-jsx": 3 },
  "bs-dependencies": ["@rescript/react", "@jsiebern/bs-material-ui"],
  "bsc-flags": ["-bs-super-errors"],
  "sources": [
    {
      "dir": "src",
      "subdirs": true
    }
  ],
  "package-specs": [
    {
      "module": "es6",
      "in-source": true
    }
  ],
  "suffix": ".bs.js",
  "namespace": true,
  "ppx-flags": [],
  "refmt": 3
}

```

It is there anything I can do to make it work? Thanks!

**Comment by jsiebern** [comment]
One of the minor breaking changes [here](https://github.com/rescript-lang/rescript-react/blob/HEAD/Changes.md) must be affecting the package. I'll get on that this weekend, thank you for bringing it up. In the meantime, please just use `reason-react@0.9` instead of `@rescript/react`. You should not feel any difference working with the "older" version at the moment I think.

**Comment by montogeek** [comment]
Thanks, got it working by doing:
1. Installing `npm i -S -E reason-react@0.9`
2. Update bs-dependency from `@rescript/react` to `reason-react`.

**Comment by jsiebern** [comment]
That's great. Just don't foget to eventually switch it back when I find the time to fix it with the bindings, the `@rescript/react` package is surely the one to move forward with :-)

**Comment by montogeek** [comment]
@jsiebern Thank you!
