### ISSUE TITLE
<MenuItem/> does not accept ~value property

### ISSUE THREAD

**Issue by mattmarcello** [jsiebern/bs-material-ui#2]
Consider the following slightly modified example from the `material-ui` documentation. 
```
<MUI.Select 
   value=(`String("")) 
   name="age">
  <MenuItem value=`String("")>
    <em>
         ( "None" |> ReasonReact.stringToElement)
    </em>
  </MenuItem>
  <MenuItem value={`String("10")}>
     ( "Ten" |> ReasonReact.stringToElement )
  </MenuItem>
  <MenuItem value={`String("20")}>
     ("Twenty" |> ReasonReact.stringToElement )
  </MenuItem>
  <MenuItem value={`String("30"}>
    ("Thirty" |> ReasonReact.stringToElement)
  </MenuItem>
</MUI.Select>;
```

This throws the following error:

```
The function applied to this argument has type
    (~className: string=?,
    ~component: [ `Element(ReasonReact.reactElement) | `String(string) ]=?,
    ~role: string=?, ~selected: bool=?, ~button: bool=?,
    ~containerComponent: [ `Element(ReasonReact.reactElement)
                         | `String(string) ]=?,
    ~dense: bool=?, ~disabled: bool=?, ~disableGutters: bool=?,
    ~divider: bool=?, ~classes: MUI.MenuItem.Classes.t=?) =>
    ReasonReact.componentSpec
    (ReasonReact.stateless,  ReasonReact.stateless,
      ReasonReact.noRetainedProps,  ReasonReact.noRetainedProps,
      ReasonReact.actionless)
This argument cannot be applied with label ~value
```

`MenuItem.d.ts` defines the following interface:

```
export interface MenuItemProps extends StandardProps<ListItemProps, MenuItemClassKey> {
  component?: React.ReactType<MenuItemProps>;
  role?: string;
  selected?: boolean;
}

```

`ListItem.d.ts` defines the following interface

```

export interface ListItemProps
  extends StandardProps<
      ButtonBaseProps & React.LiHTMLAttributes<HTMLElement>,
      ListItemClassKey,
      'component'
    > {
  button?: boolean;
  component?: React.ReactType<ListItemProps>;
  ContainerComponent?: React.ReactType<React.HTMLAttributes<HTMLDivElement>>;
  ContainerProps?: React.HTMLAttributes<HTMLDivElement>;
  dense?: boolean;
  disabled?: boolean;
  disableGutters?: boolean;
  divider?: boolean;
}

```

`ButtonBase.d.ts` defines the following interface

```
export interface ButtonBaseProps
  extends StandardProps<
      React.AnchorHTMLAttributes<HTMLElement> & React.ButtonHTMLAttributes<HTMLElement>,
      ButtonBaseClassKey
    > {
  buttonRef?: React.Ref<any>;
  centerRipple?: boolean;
  component?: React.ReactType<ButtonBaseProps>;
  disableRipple?: boolean;
  focusRipple?: boolean;
  keyboardFocusedClassName?: string;
  onKeyboardFocus?: React.FocusEventHandler<any>;
  TouchRippleProps?: Partial<TouchRippleProps>;
}
```

While, `React.LiHTMLAttributes<HTMLElement>` is [defined](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/db8be7aec245c2158be0bc2c9a8a8c3f8cdfcd96/types/react/index.d.ts#L2984) as follows:

``` 
interface LiHTMLAttributes<T> extends HTMLAttributes<T> {
   value?: string | string[] | number;
 }
```

So it seems as though the intersection type `ButtonBaseProps & React.LiHTMLAttributes<HTMLElement>` is not being properly parsed.  

Is this intended?  I'd be happy to take a crack at this issue.  Figured  I'd reach out first to see if I'm missing something here.  

Thanks!

**Comment by jsiebern** [comment]
Hi, thanks for this in-depth issue. It's definitely not intended, I checked the source as well and they did not mention the `value` prop in the prop types definition.

When I wrote the generator I couldn't quite make Typescript work for me so I used their doc generation technique (the docs are missing that `value` prop as well). I believe the easiest thing would be a pull request over at the material-ui package adding the `value` prop to List & MenuItem.

I'm totally caught up at work right now - if you want to get that going I'll rebuild the package and publish it once the pull has been accepted :-) (I need to anyway soon as they've updated to a new beta).

**Comment by mattmarcello** [comment]
That sounds good.  I can do that.  

I do wonder about a more general solution.  There will surely be other properties inherited from <HTMLAttribute> types, `tabIndex`, for instance.

**Comment by jsiebern** [comment]
Yes, most likely! I was debating wether to add `id` in general as well. I might look into Typescript deriving again, if time allows, as I've just rewritten the generator in a more general purpose way for another project.

**Comment by jsiebern** [comment]
@mattmarcello I was in need of this myself after all so I implemented a few custom props in `0.1.4-alpha1` for now

**Comment by mattmarcello** [comment]
Awesome.  Will take a look.  Did you add them by hand?  Been meaning to check out `react-docgen-typescript` when i have a little extra time but have been swamped.

**Comment by jsiebern** [comment]
Yes, I added a manual list in the generator for now, that was the quickest
way I think! That’s awesome, let me know what you find whenever you find
the time :)

**Comment by jsiebern** [comment]
Closing this for now as the features have been manually added in `v0.1.5`
