### ISSUE TITLE
Missing Bindings for popper component

### ISSUE THREAD

**Issue by gittheking** [jsiebern/bs-material-ui#20]
current bs-material-ui is missing bindings for @material-ui/core/Popper

**Comment by jsiebern** [comment]
Hmm, not sure why the generator is missing this particular one, I’ll take a look! Thanks for the notice

**Comment by jsiebern** [comment]
Could you kindly check `@next` and let me know if this issue can be closed?

**Comment by gittheking** [comment]
@jsiebern looks good to me - great work as always!
