### ISSUE TITLE
Complete bindings for theme

### ISSUE THREAD

**Issue by PTaylour** [jsiebern/bs-material-ui#22]
Continuing from conversation in https://github.com/jsiebern/bs-material-ui/issues/17 there is a little work still to be done to fully support the mui theme. 

Todo: 

- [ ] type theme object
- [ ] access theme in withStyles ppx

I'm going to start with typing the theme object

**Comment by jsiebern** [comment]
@PTaylour Have you had any progress with typing the theme object as of yet? I'm planning a new version soon that will include some better theme support so it'd be great if I could work off of anything you have so far :)

**Comment by PTaylour** [comment]
Afraid I haven't had a chance to look at it yet. Unlikely that I'll get to it before the end of the year :/

**Comment by jsiebern** [comment]
No worries, I have written an auto extractor now to deal with it :) I'll close this for now as it will be taken care of in the next release!

**Comment by PTaylour** [comment]
Awesome, your work on this project is very much appreciated :)
