### ISSUE TITLE
Trouble to use Typography.Classes

### ISSUE THREAD

**Issue by pahann** [jsiebern/bs-material-ui#23]
Maybe I'm wrong but I didn't find the way to use Typography.Classes variants. As they are not polymorphic or not exposed I don't find how to use it in order to put a class in a Typography element.

Thank you very much for your help =)

**Comment by jsiebern** [comment]
Hi, not sure I would do it like this again, but you define the classes as a list of variants!

Example:
```reason
<MaterialUi_Typography classes=[ Root(class1), Caption(class2) ]>
    "Some String"
</MaterialUi_Typography>
```

Lmk if this doesn't work for you!

**Comment by jsiebern** [comment]
For reference:
https://github.com/jsiebern/bs-material-ui/blob/master/src/MaterialUi_Typography.re#L38
