### ISSUE TITLE
MaterialUi Auto-Layout

### ISSUE THREAD

**Issue by jadiaz** [jsiebern/bs-material-ui#24]
**Auto-layout**
The Auto-layout makes the items equitably share the available space. That also means you can set the width of one item and the others will automatically resize around it.

How is this done with bs-material-ui?

**Comment by jsiebern** [comment]
@jadiaz That is a good point, I believe I removed the `true` option so they type for `xs`, `md` etc. does not need to be polymorphic! I need to think on this, I might add a variant `True` or something

**Comment by jsiebern** [comment]
Please install `@next` and see if the new `mdAuto` (available for the other sizes) will work for your use case! Closing for now, feel free to re-open if there is unexpected behaviour!
