### ISSUE TITLE
TextField has no onKeyPress

### ISSUE THREAD

**Issue by fhammerschmidt** [jsiebern/bs-material-ui#27]
Would really like to use the enter key in text fields, but the bindings offer no onKeyPress prop.

**Comment by jsiebern** [comment]
@fhammerschmidt The `onKeyPress` prop is not supported directly by MaterialUI as it seems (it doesn't even get passed on!)

You can do this though:
```ml
MaterialUi.(
  <div>
    <input onKeyPress={e => Js.log(e)} />
    <TextField
      fullWidth=true
      inputProps={
        "onKeyPress": (e: ReactEvent.Keyboard.t) => Js.log(e),
      }
    />
  </div>
)
```
