### ISSUE TITLE
SVG Icons

### ISSUE THREAD

**Issue by mscharley** [jsiebern/bs-material-ui#28]
It'd be great if the built-in SVG icon components were exposed. Currently I've inlined it 
with the SVG from https://material.io/tools/icons/

```html
<SvgIcon>
  <path fill="none" d="M0 0h24v24H0V0z"/>
  <path d="M3 5v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2H5c-1.11 0-2 .9-2 2zm12 4c0 1.66-1.34 3-3 3s-3-1.34-3-3 1.34-3 3-3 3 1.34 3 3zm-9 8c0-2 4-3.1 6-3.1s6 1.1 6 3.1v1H6v-1z"/>
</SvgIcon>
```

It'd be lovely if this could be simply:

```
<SvgIcon.AccountBox />
```

Which would pull the built-in component from `@material-ui/icons/AccountBox`.

**Comment by jsiebern** [comment]
Hi, there already is https://redex.github.io/package/bs-material-ui-icons, though it does not look like it has been maintained in a while.  Please try the package and let me know. I think it makes sense to keep it in a separate package though anyway

**Comment by mscharley** [comment]
Hmm. I agree it makes sense to keep them seperate, I only just realised that it was from a seperate package. The namespace threw me for a bit. I'll give it a shot, though it's peerDependencies say it's only for `reason-react 0.3.x`. Looks like someone has done a PR to update it. Anyway, I'll close this and investigate further. Thanks for the pointer.

**Comment by mscharley** [comment]
In light of the original dev not seeming to be responsive (ready-to-go update PR sitting cold for over a month) I'm taking the PR and running with it. If someone else finds this, I'm publishing updated packages as [`@mscharley/bs-material-ui-icons`](https://www.npmjs.com/package/@mscharley/bs-material-ui-icons).
