### ISSUE TITLE
`TablePagination` component doesn't have the correct bindings for `onChangePage`

### ISSUE THREAD

**Issue by gittheking** [jsiebern/bs-material-ui#3]
Currently, `TablePagination` has a binding signature of `unit => unit` so there is no way to access the value of page as described in the [material-ui-next docs](https://material-ui-next.com/api/table-pagination/). I'd expect to be able to define the event like:
```
<MaterialUi.TablePagination
  onChangePage=(
    (_event, page) => self.send(UpdatePage(page))
  )
  ...
>
```
instead I get a bucklescript error
```
This function expects too many arguments, it should have type unit => unit
```
I've been able to make it work in the meantime by creating my own minimal binding:
```
module TablePaginationCustom = {
  [@bs.module "material-ui/Table/TablePagination"]
  external reactClass : ReasonReact.reactClass = "default";
  let make =
      (
        ~colSpan: int,
        ~count: int,
        ~rowsPerPage: int,
        ~page: int,
        ~onChangePage: (ReactEventRe.Mouse.t, int) => unit,
        children,
      ) =>
    ReasonReact.wrapJsForReason(
      ~reactClass,
      ~props={
        "colSpan": colSpan,
        "count": count,
        "rowsPerPage": rowsPerPage,
        "page": page,
        "onChangePage": onChangePage,
      },
      children,
    );
};
```

I'm still super new to Reason, so please let me know if I'm misunderstanding some concepts here.

Thanks!

**Comment by gittheking** [comment]
@jsiebern thanks for getting back to me, this is a really awesome project! I'm still very new to the Reason world and this is a huge help for me.

**Comment by jsiebern** [comment]
Thank you! And let me tell you - I've been exactly where you're at. I couldn't really start to adopt Reason because my required UI Library didn't have any proper bindings and writing them by hand seemed crazy...

**Comment by jsiebern** [comment]
Should be fixed in `0.1.61`, thank you :)

**Comment by Sarazh** [comment]
Checkbox has similar problem for `onChange` function. The type is `onChange: option(ReasonReact.Callback.t(ReactEventRe.Form.t))=?`, which should be `onChange: option((ReactEventRe.Mouse.t, bool) => unit)=?`

**Comment by jsiebern** [comment]
@Sarazh Thanks for the report, fixed it 👍

**Comment by Sarazh** [comment]
The new version breaks functions in some components, e.g. in Select component, 
the following type are not function any more.  

``` 
     ~onChange: ReactEventRe.Form.t=?,
      ....
      ~onBlur: ReactEventRe.Focus.t=?,
      ~onEmpty: ReactEventRe.Synthetic.t=?,
      ~onFilled: ReactEventRe.Synthetic.t=?,
      ~onFocus: ReactEventRe.Focus.t=?,
      ~onKeyDown: ReactEventRe.Keyboard.t=?,
      ~onKeyUp: ReactEventRe.Keyboard.t=?,

```

which are correct in previous veriosn: 

``` 
     ~onChange: ReasonReact.Callback.t(ReactEventRe.Form.t)=?,
      ....
      ~onBlur: ReasonReact.Callback.t(ReactEventRe.Focus.t)=?,
      ~onEmpty: ReasonReact.Callback.t(ReactEventRe.Synthetic.t)=?,
      ~onFilled: ReasonReact.Callback.t(ReactEventRe.Synthetic.t)=?,
      ~onFocus: ReasonReact.Callback.t(ReactEventRe.Focus.t)=?,
      ~onKeyDown: ReasonReact.Callback.t(ReactEventRe.Keyboard.t)=?,
      ~onKeyUp: ReasonReact.Callback.t(ReactEventRe.Keyboard.t)=?,

```

**Comment by jsiebern** [comment]
Yes, sorry, I couldn't fix it last night, I'll push a fix in a little bit

**Comment by jsiebern** [comment]
It should work fine now!

**Comment by Sarazh** [comment]
Thank you very much. It works.
