### ISSUE TITLE
Unsafe styles problems after upgrading to 1.0

### ISSUE THREAD

**Issue by unodgs** [jsiebern/bs-material-ui#35]
Hi! I used safe styles but when I needed linux CI pipeline back then when no ppx for linux was available I switched to unsafe styles. And it worked until last update to 1.0 :) It looks like my styles are not applied. Example on github for unsafe style is quite old like it was not tested with recent changes. All my components use following pattern:
```
    render: self => <MaterialUi.WithStyles
        classes=[{
            name: "mystyle",
            styles: Style.make(
                ~minHeight="850px",
                ~position="relative",
                ()
            )
        }]
        render={classes => <div className=classes##mystyle/>}
       />
```
I would be very glad if it stared to work again - my codebase is too big now for going back to safe styles.

**Comment by unodgs** [comment]
Btw.. if my component has  ```classesWithTheme={theme => []}``` it fails in runtime with error: `["Not_found", -6, tag: 248]`

**Comment by jsiebern** [comment]
Hey, thanks for the report!

I had to go back to the current styling method and it works stable enough for me that I put `1.0.0` out. Can you try the latest release and report back if that fixes the issues?

You can look at the examples for styling by cloning this repo and going `yarn install`, `yarn examples`. Both unsafe techniques work in that context.

**Comment by unodgs** [comment]
Thx! It's much better now, but there is one serious problem and I think it's also fault of the new version. If I call a function on a record passed through props to the child component (I'm passing a store) I get maximum rerender depth error from react. This code looks like this:
```
let make = (~store: Store.t, children) => {
    ...
    render: self => <MaterialUi.WithStyles
        classes=[...]
        render={ classes => <SomePage store>}
   />
}
```
SomePage calls in `didMount` `store.send(someaction)`.
If I remove from parent component `MaterialUI.WithStyles` and left only `render: self => <SomePage store/>` then everything comes back to normal.
WIth 0.4.2 of material ui everything was fine. If you need better test case let me know.

**Comment by jsiebern** [comment]
Sorry for the delay. Could you update to the latest version and lmk if the issue still persists?

**Comment by unodgs** [comment]
Still the same problem, I'll prepare a test case to make it easier for you to check.

**Comment by unodgs** [comment]
OK, I found finally some time to make a minimal test case:
[bs-material-ui-test-case.zip](https://github.com/jsiebern/bs-material-ui/files/3120028/bs-material-ui-test-case.zip)
Tu run it please do:
```
yarn install
yarn dev
open localhost:8080
```
If you open it the first time you'll notice maximum depth error in the console (and some other warnings)
There are two ways to get rid of it. First is to comment line 8 in `userList.re`:
`store.send(Action.WORKING(true));`
Then you should see `everything works`
Second way is to rename current make function into `make3` and rename `make2` into `make` in `main.re`
This second version of `main` component doesn't use `MaterialUi.WithStyles`. And that version works perfectly too.

Of course every case works correctly with bs-material-ui 0.4.2. It all started to break with newer versions.

I hope this will help you somehow to identify the problem :)

**Comment by unodgs** [comment]
I also tried safe styles:
```
let make = (children) => {
    ...component,
    render: self =>
        <StyledExample>
            ...{classes =>
                <div>
                    <main>
                        {children}
                    </main>
                </div>
            }
         </StyledExample>
};
```
and this one works too :) So there must be sth wrong with `MaterialUi.WithStyles`

**Comment by jsiebern** [comment]
@unodgs Is this issue still relevant?

**Comment by unodgs** [comment]
Issue still exists in the latest stable version and I'm still on 0.4.2 because of that :( It would be great to have this fixed (especially that safe styles don't work in windows env). But if that's problematic maybe it's not worth wasting time on it - eventually I will need to switch to reason react 0.7 with hooks so I will be forced to make bigger refactoring anyway. Did you try my test-case?

**Comment by jsiebern** [comment]
Sorry to say, but I'll deprecate the version of the bindings this issue is based on in the next version. Therefore I'll close this issue, I hope you have upgraded anyway by now 😅

**Comment by unodgs** [comment]
Yes, I migrated and now everything is working again :) I think I dug in to the root cause but I wasn't able to fix it anyway. Let's close it.
