### ISSUE TITLE
export createStyledWithTheme was not found in @material-ui/styles

### ISSUE THREAD

**Issue by jcdoig** [jsiebern/bs-material-ui#36]
I'm received the following warning in webpack when I try to compile my code

```
WARNING in ./node_modules/@jsiebern/bs-material-ui/src/MaterialUi_WithStyles.bs.js 75:13-41
    "export 'createStyledWithTheme' (imported as 'Styles') was not found in '@material-ui/styles'
     @ ./src/core/Styles.bs.js
     @ ./src/app.bs.js
     @ ./src/index.bs.js
```

indeed '@material-ui/styles' does not contain 'createStyledWithTheme'.
https://github.com/mui-org/material-ui/blob/master/packages/material-ui-styles/src/index.js

```javascript
export { default as createGenerateClassName } from './createGenerateClassName';
export { default as createStyles } from './createStyles';
export { default as install } from './install';
export { default as jssPreset } from './jssPreset';
export { default as makeStyles } from './makeStyles';
export { default as styled } from './styled';
export { default as StylesProvider } from './StylesProvider';
export { default as ThemeProvider } from './ThemeProvider';
export { default as useTheme } from './useTheme';
export { default as withStyles } from './withStyles';
export { default as withTheme } from './withTheme';
```

I'm using:
"@material-ui/styles": "3.0.0-alpha.3",
"@jsiebern/bs-material-ui": "1.0.0-beta.4",
"@jsiebern/bs-material-ui-ppx": "^1.0.2",

My code compiles and works as expected when I use webpack development mode (it does show the working but it works), but when I compile my code in webpack's production mode all the styles are wrong and the application looks broken.

**Comment by jsiebern** [comment]
I've had some troubles and back and forth myself with the new styling solutions, so I went back to the old way of doing things. Could you please install the latest version and report back if that fixed your issues? Thank you!

**Comment by jcdoig** [comment]
It did fix the issue, Awesome Job. Thanks and happy new year!
