### ISSUE TITLE
MaterialUi_Icons should be MaterialUi.Icons

### ISSUE THREAD

**Issue by RicheyRyan** [jsiebern/bs-material-ui#38]
Hey, great work on the library so far. I really appreciate the good work!

When I try and use `Icons` from MaterialUI the error is that the module is unbound.

It doesn't seem to be exported from `MaterialUi.re`. However, it is available at MaterialUi_Icons.

I can make a PR to add it just below the `Icon` module:
https://github.com/jsiebern/bs-material-ui/blob/07b14ab57557a226fccc5c016b2adb28594966a5/src/MaterialUi.re#L47

Let me know if that makes sense and sounds good. If I'm doing something silly let me know 😄

**Comment by jsiebern** [comment]
FYI: I have removed all icons from 1.1.0 and am recommending @mscharley 's package now in the readme. It has everything that is needed, decent compile speeds and I would have done it rather similar anyway :)

**Comment by RicheyRyan** [comment]
Cool, thanks for getting back to me! I'll check out the other package. Thanks for your work on this one!
