### ISSUE TITLE
TableCell `align` prop

### ISSUE THREAD

**Issue by actionshrimp** [jsiebern/bs-material-ui#39]
Hey - this is awesome, thanks very much for making it!

I'm trying to figure out how to set 'align' on the `TableCell` component, as mentioned here:
https://material-ui.com/api/table-cell/ - as it appears under 'props' on those docs, I'd expect to be able to do:
```
<TableCell align=`Center>...</TableCell>
```

Should this instead be done using the styling framework? I tried setting a className that set textAlign as I wanted, but it was overridden by a higher precedence style rule - I'm still getting my head round all of the 'vanilla' material-ui concepts so ignore this part if it makes no sense 😄

**Comment by jsiebern** [comment]
@actionshrimp This is exactly how it should work! Please try updating to the latest version I just pushed and let me know if this still doesn't work :)

**Comment by actionshrimp** [comment]
That's done the trick - thanks very much!
