### ISSUE TITLE
No docs appear on NPM

### ISSUE THREAD

**Issue by Will-W** [jsiebern/bs-material-ui#42]
I normally find packages and their docs via NPM in the first instance. If I do that for bs-material-ui now, I only see:

`Unable to find a readme for @jsiebern/bs-material-ui@1.1.0`

I think this is also having the effect that it doesn't appear in the top few results of Google any more (which is how I found it originally).

**Comment by jsiebern** [comment]
I totally forgot to include the readme in the package after the refactor!

Thanks a bunch for pointing that out :)

**Comment by jsiebern** [comment]
Pushed a version that should fix that
