### ISSUE TITLE
PPX build fails at the end on Linux

### ISSUE THREAD

**Issue by Will-W** [jsiebern/bs-material-ui#43]
When the ppx is added (and then built) on linux, at the end the following error happens:
`cp: cannot stat './lib/bs/native/ppx_withStyles.native': No such file or directory`

This is because the command is written with a capital S and linux is case-sensitive.

This issue had previously been reported and fixed before the repos are merged (https://github.com/jsiebern/reason-mui-withstyles-ppx/pull/4), and the fix hasn't been brought over.

I'm about to do a pull request.

**Comment by jsiebern** [comment]
Published a new version of the ppx with the PR included, that should fix it.
