### ISSUE TITLE
Dynamic access to classes

### ISSUE THREAD

**Issue by studious** [jsiebern/bs-material-ui#46]
I would like to emulate the following in ReasonML but records can't be accessed dynamically like in JS
```
const expandedClass = expanded ? 'open' : 'closed'

<div className={classes[expandedClass]}>
```
Is there a way I can dynamically select one of the Style Class Records? Would they need to be Js.Dict.t instead?

I've resorted to inline styles for the dynamic styling I need.

Thanks

**Comment by jsiebern** [comment]
Hi, couldn't you just do:

```reason
let expandedClass = expanded ? classes.open : classes.closed;

<div className=expandedClass>
```

I assume you mean the styles record coming from the ppx, correct?

**Comment by studious** [comment]
Sorry I should have given a more complete example.

I was making composable helper functions like `makePassClass(item)(score->getPassRate)` to get a variety of different classnames that I was going to use to access the classes `rowGreen, rowOrange, rowRed, cellGreen, cellOrange, cellRed, ...`.

After posting my question I starting moving in the direction you suggest as well. It's not quite as composable but it will do the trick. I need to pattern match per (row, cell). I suppose they could be combined using a tuple.

```
let getRowClass(classes, score->getPassRate) =>
  switch (rate) {
  | Fail => classes.rowRed
  | Pass => classes.rowOrange
 ...};

let getCellClass(classes, score->getPassRate) =>
  switch (rate) {
  | Fail => classes.rowRed
  | Pass => classes.rowOrange
 ...};
```

Anyway thanks for the response.

**Comment by jsiebern** [comment]
No worries, thanks for the explanation!
