### ISSUE TITLE
ppx issue on windows

### ISSUE THREAD

**Issue by xavierzwirtz** [jsiebern/bs-material-ui#47]
I am attempting to use `bs-material-ui-ppx` on Windows 10, but cant seem to make it work without hacking it up. With a stock install of the package, and adding `"ppx-flags": ["@jsiebern/bs-material-ui-ppx/ppx"]`, to my `bsconfig.json` I get this error message when compiling:
```
'{bs-material-ui-ppx-path}\ppx' is not recognized as an internal or external command
```
However, if I move the ppx file to ppx.exe, and change the ppx-flags path to end with `.exe` it works.

**Comment by liilac** [comment]
Hi,

I've encountered a related issue attempting to use the `bs-material-ui-ppx` package on Windows 10.

Output from attempting to run `yarn add --dev @jsiebern/bs-material-ui-ppx` is [here](https://gist.github.com/liilac/f042127cdfcb2834b363ba9209d35f14).

Relevant snippets below:
```
PS X:\path\to\project-dir> yarn add --dev @jsiebern/bs-material-ui-ppx
yarn add v1.15.2
[...]
[4/4] ⠐ @jsiebern/bs-material-ui-ppx
error X:\path\to\project-dir\node_modules\@jsiebern\bs-material-ui-ppx: Command failed.
Exit code: 1
Command: bsb -make-world -backend native && cp ./lib/bs/native/ppx_withstyles.native ./ppx
Arguments:
Directory: X:\path\to\project-dir\node_modules\@jsiebern\bs-material-ui-ppx
Output:
[...]
[6/6] Building ppx_withstyles.native.exe
```

Notably, see the last line, `ppx_withstyles.native.exe` is built with the `.exe` extension

**Comment by xavierzwirtz** [comment]
This is resolved in the `hooks` branch.
