### ISSUE TITLE
Why is not using the ppx for withStyles unsafe?

### ISSUE THREAD

**Issue by anisjonischkeit** [jsiebern/bs-material-ui#48]
Hey, still early days for my use of these bindings and I'm deciding whether it is worth it to use the ppx (I don't have a strong reason not to use it but also don't have a strong reason to use it). The API looks almost the same to me so I'm wondering what makes it unsafe?

**Comment by jsiebern** [comment]
Hey, glad you're here, early days or not ;-)

So unsafe refers mostly to losing the names of your classes. You could miss spell a name of a class in the render method with the unsafe bindings. This doesn't happen with the PPX as a record of class names is being passed into the render function.

The PPX is the reason way (full compiler complaining), without the hassle of converting the input to the HOC yourself.

**Comment by anisjonischkeit** [comment]
Ahh, I didn't realise `##className` wouldn't guarantee that `className` exists on the object. Thanks!
