### ISSUE TITLE
The new reason  react hooks

### ISSUE THREAD

**Issue by Tevinthuku** [jsiebern/bs-material-ui#49]
I'm getting this error upon attempting to use the bindings with the new reason react hooks template 

![image](https://user-images.githubusercontent.com/12128153/56869259-02744380-6a07-11e9-91c2-221cba20d08b.png)

I'm open to helping in any API changes that are necessary to enable compatibility with the new version of Reason React

**Comment by jsiebern** [comment]
Hi, please try:

yarn add @jsiebern/bs-material-ui@hooks

The hooks version is currently on a separate branch.

**Comment by Tevinthuku** [comment]
Awesome, I hadn't seen that. thanks for the good work

**Comment by tejesh014** [comment]
Hi, Are planning on merging this to master. Needed this for my code that currently uses hooks.
