### ISSUE TITLE
Step bindings cause an error at runtime.

### ISSUE THREAD

**Issue by anisjonischkeit** [jsiebern/bs-material-ui#50]
Inserting a `<Step />` I keep getting this error. looks like something to do with `[@bs.deriving jsConverter]`. Any ideas?

<img width="636" alt="Screenshot 2019-05-06 at 15 09 54" src="https://user-images.githubusercontent.com/22971353/57227285-4c65b680-7011-11e9-879d-bec95998e75d.png">

**Comment by jsiebern** [comment]
I assume you're on the hooks branch, right? I'll check it as soon as I can

**Comment by anisjonischkeit** [comment]
Yeah, I'm on the hooks branch. Thanks heaps!

**Comment by anisjonischkeit** [comment]
I actually think this is a BuckleScript issue. I've raised it here: https://github.com/BuckleScript/bucklescript/issues/3548

**Comment by contrastBro** [comment]
Hi,
the same happens also if you try to use <MaterialUi_Tab />
"textColorToJs" triggers binarySearchAux

**Comment by bobzhang** [comment]
See my comments about how to debug such things, can you log the input ?

**Comment by anisjonischkeit** [comment]
I got some time today to take a closer look at this. Looks like the orientationToJs function works fine when using `"bs-platform": "5.0.5-beta.1"`. 

There is still a problem. The thing being passed into orientationToJs (`type orientation`) should be a number when you `Js.log` it but when orientation isn't specified (ex. `<Step>`) it is actually the string "vertical". I don't know where this default value comes from (I was expecting a `None` as prop) and somehow it typechecks that there is a valid `option(orientation)` being passed in to `make`.

**Comment by jsiebern** [comment]
Thanks for taking a look. So sorry guys, being overwhelmed at work right now. I'm making some progress little by little upgrading to v4 though, I'll try to include a fix to this as well!

**Comment by anisjonischkeit** [comment]
Do you understand what the problem is or should I keep digging whenever I get time?

**Comment by zth** [comment]
I have the same problem and would gladly help anyway I can. Just let me know!

@jsiebern thank you for this lib btw, it's really great. Happy user over here!

**Comment by anisjonischkeit** [comment]
Material-ui's `Step` and `Stepper` components use React.cloneElement to [set the orientation prop](https://github.com/mui-org/material-ui/blob/08bdf768f6b79cc269d62ef059eae4273d5dbd9f/packages/material-ui/src/Stepper/Stepper.js#L88) of their children if the prop isn't present. So the problem lies in the fact that `orientation="vertical"` is being sent to a ReasonReact component that expects a variant (compiled to something like `orientation=-1010337642`.

Some Possible Solutions (although neither are great):
- Make orientation non-optional so that the prop never gets overwritten
- Check what type the orientation prop has and if it is a string ("vertical" | "horizontal") call orientationFromJs (not great since we rely on the compiler not changing the way it deals with variants)

Any other ideas @jsiebern?

As a work around for now, anyone experiencing this, just specify orientation on all children of `Stepper` and `Step`

**Comment by jsiebern** [comment]
@anisjonischkeit Thanks for the in depth  explanation, that helped out a lot. I have solved this with a good enough compromise I believe. Basically all Step components now have their orientation prop parsed like this:

```reason
~orientation=?
  orientation->(
                  Belt.Option.map(v =>
                    switch (v->Obj.magic->Js.Json.classify) {
                    | JSONString(str) => str
                    | _ => orientationToJs(v)
                    }
                  )
                ),
```

I don't think theres a good way around their technique of using `React.cloneElement`. I hope I'll be ready for v4 soonish, thanks guys!

**Comment by jsiebern** [comment]
PS: Fixed it for tabs as well, let me know in this issue if you guys find anymore examples of those pass through props

**Comment by anisjonischkeit** [comment]
Thanks @jsiebern, looks good to me!

**Comment by PierreGuttAlive** [comment]
Hi! Just got this issue in Tab component, any progress on it?

**Comment by anisjonischkeit** [comment]
@PierreGuttAlive I believe this is fixed. Are you on the latest commit on the hooks branch?

**Comment by PierreGuttAlive** [comment]
I am using version 1.1.0-hooks.3

**Comment by jsiebern** [comment]
Should be fixed in the latest `@hooks` from NPM
