### ISSUE TITLE
Postinstall script calling bsb instead of bsb-native within Docker container.

### ISSUE THREAD

**Issue by Phylodome** [jsiebern/bs-material-ui#53]
I'm encountering a strange issue when I attempt to containerize a project that includes `bs-material-ui-ppx`. 

Outside the containerized environment everything works fine, but when I try to build a Docker container using the `node:11` image, I encounter an issue when the `postinstall` script attempts to build via `bsb-native`. It appears to execute the default `bsb` from `bs-platform`, per this error message about not supporting the `-backend` option:

```
> bsb-native@4.0.1100 postinstall /physis/node_modules/@jsiebern/bs-material-ui-ppx/node_modules/bsb-native
> node postinstall.js

Unzip successful.

> @jsiebern/bs-material-ui-ppx@1.0.4 postinstall /physis/node_modules/@jsiebern/bs-material-ui-ppx
> bsb -make-world -backend native && cp ./lib/bs/native/ppx_withstyles.native ./ppx

/physis/node_modules/@jsiebern/bs-material-ui-ppx/node_modules/bsb-native/lib/bsb.exe: unknown option '-backend'.
Usage : bsb.exe <bsb-options> -- <ninja_options>
```

However, the executable path mentioned in the logs (`/physis/node_modules/@jsiebern/bs-material-ui-ppx/node_modules/bsb-native/lib/bsb.exe`) implies that the `bsb.exe` from `bs-material-ui-ppx`'s `node_modules` is raising this error. But if that were the case, `bsb.exe` would know how to handle the `-backend` flag. It appears something's lying to us...

This seems related to [this issue](https://github.com/osener/ppx-tea-jsx/issues/1), though a definitive conclusion wasn't reached in that thread.

Do you have any ideas regarding why this might occur?

**Comment by Schmavery** [comment]
iiuc both `bsb-native` and `bs-platform` put a executable called `bsb` in `node_modules/.bin`. Could there be a difference in how different versions of npm resolve this collision maybe, resulting in running the wrong one in the postinstall? Pretty much a guess.. and the point you make about the path in the logs does seem to indicate that it's running bsb-native.
Is there a difference between the node/npm version in an environment where it runs and the one in the docker container?

**Comment by Phylodome** [comment]
Yeah, it’s definitely the case that NPM is trying to “optimize” the dependency graph by placing both executables at the root bin.

Best I can tell by scouring the web for similar issues, it’s possibly an issue with platform discrepancies in how symlinking of the executable paths works.

To be honest, though, this just forced me to ask the deeper question of: “do I want to depend on a part of this lib that requires an alternate (and now generally unmaintained and out of date) parallel build system?”

My answer was no, and I’m replacing the withStyles approach using bs-css. This carries with it its own costs, but given Material UI now supports injecting styles into the beginning of the doc HEAD rather than the end, overriding component styles with other libs becomes far easier.

That is in addition to the fact that moving forward, this lib should converge upon the hooks pattern of style overrides anyhow.

**Comment by Phylodome** [comment]
Perhaps this is a decent opportunity to ask @jsiebern about his future plans for this repo:

- Are you still planning to maintain this lib alongside the evolution of MaterialUI? For example, [v4 was just released](https://medium.com/material-ui/material-ui-v4-is-out-4b7587d1e701), with [changes](https://material-ui.com/guides/migration-v3/) that will require some minor API updates.
- When do you foresee the hooks branch becoming the primary source of truth for this repo?
- Do you still feel the inclusion of `bsb-native` is a viable path forward, given its development appears to increasingly lag behind that of `bs-platform`?
- Will the HOC `withStyles` ppx approach remain the primary mode of styling for this lib? It seems like leveraging hooks may provide a simpler and more maintainable path moving forward, and allow for the removal of the dependency upon ppx, which forces the tradeoff between shipping multiple binaries / depending on `bsb-native`.

Would appreciate your thoughts, as I work through my own plans with respect to the use of this lib.

**Comment by Phylodome** [comment]
@jsiebern Could you provide any information with respect to the questions above? Apparently there are at least a few of us who are curious.

Would you like help managing this repo? Would it be better for us to fork and evolve things separately? It would be great to hear from you before needlessly forking this project any further.

**Comment by jsiebern** [comment]
@Phylodome yes, sorry about not being as active lately - work has been quite overwhelming.

I absolutely plan on keeping these bindings up to date, as I use them myself quite heavily. I'll try answering your questions as best I can for now:

> Are you still planning to maintain this lib alongside the evolution of MaterialUI? For example, v4 was just released, with changes that will require some minor API updates.

Yes.

> When do you foresee the hooks branch becoming the primary source of truth for this repo?

As soon as I have a stable version of v4 running on it. I will have a lot more time to dedicate to OS again in around 2 - 3 weeks. I'll try get this out before though.

> Do you still feel the inclusion of bsb-native is a viable path forward, given its development appears to increasingly lag behind that of bs-platform?

Honestly: This is beyond my area of expertise (building native execs that is). I have lent this "trick" of compiling PPXs on the fly from Jared, who relies on it in basically all of his PPXs. If you have a way of providing a better solution - I'd love the help (maybe have pre-compiled binaries).

So all in all, I don't care too much about the outdated-ness of bsb-native as it does its job. What bugs me is the time it takes to first compile it and only then being able to compile the PPX.

> Will the HOC withStyles ppx approach remain the primary mode of styling for this lib? It seems like leveraging hooks may provide a simpler and more maintainable path moving forward, and allow for the removal of the dependency upon ppx, which forces the tradeoff between shipping multiple binaries / depending on bsb-native.

I have thought about this and still came to the conclusion that the PPX is necessary to provide type safety (to reliably get the classnames). I think I have found a good compromise of just adding a hook function to the generated Module (See [this file](https://github.com/jsiebern/bs-material-ui/blob/hooks/public/bs-material-ui/examples/ExampleSelect.re#L30) for an example).

I would also love to replace the `ReactDOMRe.Style.t` implementation with something like `bs-css`. This could work by leveraging something like https://github.com/minima-app/re-css .

> Would you like help managing this repo? Would it be better for us to fork and evolve things separately?

So yes, if someone could help out resolve this frustrating build process thing...

--- 

I hope that answers your questions mostly and gives some insight as to what my intentions are. MUI is changing a lot at the moment (for example: I will probably have to do some workarounds for `4.2` so I have to stay with the latest `4.1x` atm.), and we will always lag behind a bit with these bindings. I do not plan on leaving it *that* far behind again though.

**Comment by Phylodome** [comment]
Thanks for the answers. I look forward to seeing / familiarizing myself w/ the stable v4 version.

With respect to the PPX, I'm just dipping into those waters myself, so I do not have any suggestions with respect to this other than perhaps pre-building platform-specific binaries such that `bsb-native` isn't called during install. Out of curiosity here, have you had any luck containerizing this library? I'd be curious about the node container version that worked for you, as I wasn't able to find one.

Also curious: is adding support for [MaterialUI's new CSS-injection order](https://material-ui.com/styles/advanced/#css-injection-order) within your present scope of work? I'm presently using `bs-css` directly, though unfortunately must rely on `important` statements to override MUI styles when necessary. This one change alone would allow for a far greater level of interop w/o any explicit changes to the current `withStyles` paradigm.

That said, moving forward, I'd be interested in working toward a unification of `bs-css` with `bs-material-ui`, as I've grown quite fond of the "css-as-typed-functions-with-variants" approach.

**Comment by jesusem15** [comment]
I have the same issue when I'm trying to run a project inside of a docker container.

node: v8.12.0
yarn: 1.12.1
bsb: 5.0.6

I got this error:
```
error /myproject/node_modules/@jsiebern/bs-material-ui-ppx: Command failed.
Exit code: 2
Command: bsb -make-world -backend native && cp ./lib/bs/native/ppx_withstyles.native ./ppx
Arguments:
Directory: /myproject/node_modules/@jsiebern/bs-material-ui-ppx
Output:
/myproject/node_modules/@jsiebern/bs-material-ui-ppx/node_modules/bsb-native/lib/bsb.exe: unknown option '-backend'.
```

My container has installed the same versions that my local machine, but on my machine is able to run the project without problems, do you know any solutions?

**Comment by Phylodome** [comment]
@jesusem15 No, after suffering through many hours of attempting to debug this at multiple levels of analysis, I just decide to rip out the `WithStyles` aspect of this library, whose usage triggers the necessity to include the PPX dep.

Instead we just use `bs-css`, and have rolled our own `StylesProvider` so that we may use the `injectFirst` feature of Material UI that injects custom styles before MUI's own, such that overrides become relatively simple.

It's not the most elegant solution, but it's pragmatic, and `bs-css`'s typed styles are a pleasure to use.

**Comment by jsiebern** [comment]
Hey guys, I have shamelessly stolen from `graphql_ppx` and implemented Github actions in order to ship prebuilt binaries. Could you guys test the new system and report back if it works okay?

`yarn add @jsiebern/bs-material-ui-ppx@test`

**Comment by jsiebern** [comment]
Closing as I have released the 2 version ppx now
