### ISSUE TITLE
Tabs Component doesn't highlight selected tab

### ISSUE THREAD

**Issue by roopana12** [jsiebern/bs-material-ui#54]
Using properties like `indicatorColor` or `textColor`, the **_selected Tab_** doesn't get _highlighted_.

I tried to use the **Tab component** by cloning this repo and editing one of the files in the examples folder https://github.com/jsiebern/bs-material-ui/tree/master/public/bs-material-ui/examples
And noticed this below output
<img width="283" alt="Screenshot 2019-05-28 at 2 21 04 PM" src="https://user-images.githubusercontent.com/51114473/58464725-db1eac80-8153-11e9-802e-d609ebd221e2.png">

Below are the versions I have used to try the `Tab Component`
material-ui - 3.9.2
jsiebern/bs-material-ui - 1.1.1

**Comment by jsiebern** [comment]
This should be fixed in the next release (see #50 ), closing it for now.
