### ISSUE TITLE
theming

### ISSUE THREAD

**Issue by mattmarcello** [jsiebern/bs-material-ui#6]
I see that there a variety of to-do items related to theming.  Have you decided on an execution plan?  If so, perhaps it would be good to document it here?

In the meantime, going to read the code to see what's possible.  

Thanks!

**Comment by jsiebern** [comment]
Hi, thanks for the input. I don't use theming at all at work (which I made the bindings for) so I'm not too familiar with the options and what the focus needs to be on.

Do you have any suggestions on how to tackle the various theming layers?

**Comment by jsiebern** [comment]
@mattmarcello I've had the need to use some different colors now as well. The easist thing to do right now would be:

```reason
[@bs.module "@material-ui/core/styles"]
external createMuiTheme : Js.t({..}) => Js.t({..}) = "createMuiTheme";

let theme =
  createMuiTheme({
    "palette": {
      "primary": {
        "main": "#0096F0",
      },
      "secondary": {
        "main": "#E7414D",
      },
    },
  });

<div className="app-container">
  <MaterialUi_MuiThemeProvider theme=(`ObjectGeneric(theme))>
    /* components... */
  </MaterialUi_MuiThemeProvider>
</div>
```

It's just that you'll have to write the `createMuiTheme` binding yourself. I'll close this for now as that is a workable way (I'll probably factor this in somehow soon).

**Comment by mattmarcello** [comment]
Thanks for following up.
