### ISSUE TITLE
Large bundle size overhead if using withStyles ppx 

### ISSUE THREAD

**Issue by MargaretKrutikova** [jsiebern/bs-material-ui#64]
I was trying out the hooks branch and used `[%mui.withStyles...]` in quite a lot of my components to override styling. I checked the bundle distribution with `source-map-explorer` and it showed that the components that used the `ppx` (around 10-15 in total) where larger than `react-dom` itself.

It appears that the generated javascript from `[%mui.withStyles...]` has a function `style` that takes all possible `css` props (in total 348) and calls the function for each class with missing parameters as `undefined`, so it looks like this:
```reason
function style(prim, prim$1, prim$2, prim$3, prim$4, prim$5, prim$6, prim$7, ..., prim$347) {
  var tmp = { };
  if (prim !== undefined) {
    tmp.azimuth = Caml_option.valFromOption(prim);
  }
  if (prim$1 !== undefined) {
    tmp.background = Caml_option.valFromOption(prim$1);
  }
...
style(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, ...)
```

The function `style` is duplicated in each component that uses the `ppx` with `[%mui.withStyles...]`. This contributes immensely to the overall bundle size.

Is it the expected behavior? Or have I missed some bit of configuration?

I really enjoy working with `bs-material-ui` and can't imagine working on my projects without it, but the issue with the bundle size is really concerning. I am happy to help further investigate and improve it though!

**Comment by jsiebern** [comment]
Hi, thanks for reporting, that is definitely not intended behaviour 😂 I'll look into it and abstract that function as soon as I have the time.

**Comment by jsiebern** [comment]
@MargaretKrutikova Hi again. I'm trying to replicate this issue, but I can't get it to generate this function. Could you provide a repro with the current version?

**Comment by MargaretKrutikova** [comment]
You can check [this repo](https://github.com/MargaretKrutikova/bs-react-netlify-identity/tree/mui_ppx/examples/material-ui) at that specific branch, since I removed `mui_ppx` from `master`. 

I have the latest hooks branch, `1.1.0-hooks.8`, just tested it again with the same result. Thanks for looking into this!

**Comment by MargaretKrutikova** [comment]
Wow, I just realized why it was generating that huge function in every file where I used the ppx. This line: 
```
let style = ReactDOMRe.Style.make;
```
just copies that huge function into every file and I had it defined like this literally in every file 😆 

It has nothing to do with your ppx, just me who was really dumb. I am very sorry for reporting this issue, hope it didn't take much of your time to look into it!

**Comment by jsiebern** [comment]
@MargaretKrutikova Don't worry about it, **** happens 😂  

I usually use `bs-css` to generate my styles. Yes, it has a little overhead, but it's soundly typed and works well. I have a helper function to interop with the ppx defined like this:

```reason
external convertAnyToReactStyle: 'a => ReactDOMRe.Style.t = "%identity";

let css = (ruleset: list(Css.rule)) =>
  ruleset->Css.toJson->convertAnyToReactStyle;
```

**Comment by MargaretKrutikova** [comment]
Oh, I absolutely love `bs-css` 😄 Wow, nice, thanks for the example code, will try it!

Since we are at it anyway, why does this `let style = ReactDOMRe.Style.make;` copy the whole function instead of just creating a reference to it? Is it something `OCaml` does per default or is it `Bucklescript`?

**Comment by jsiebern** [comment]
Good question... It's definitely Bucklescript though. The language gods are discussing this exact topic over on twitter right this moment (well, to be fair, it's about modules and how that works, but the underlying mechanic must be connected).

https://twitter.com/bobzhang1988/status/1184029044943097856

**Comment by MargaretKrutikova** [comment]
Oh cool, thanks for the link! I will definitely remember this lesson now 😃
