### ISSUE TITLE
ppx_WithStyle doesn't work for linux

### ISSUE THREAD

**Issue by Sarazh** [jsiebern/bs-material-ui#7]
Current ppx works with Mac, but it has problem to run on linux. Do you have a version for linux??

**Comment by jsiebern** [comment]
@Sarazh Phew, thats a tough one, I don't have any experience with compiling to different targets, the ppx was more of an experiment! What does it say on Linux, I have no easy way of testing this right now.

**Comment by unodgs** [comment]
This is the real problem for my jenkins run on linux... Switching to unsafe styles is not the path I would like to take :)

**Comment by liamcurry** [comment]
I was able to get this working on Arch Linux by recompiling the ppx generator on my machine. I created PR #14 that adds the compiled binary to this repo. @Sarazh @unodgs could you checkout that branch and see if the new binary works on your machine?

**Comment by jsiebern** [comment]
That’s awesome, thanks for the PR! After studying the bs_css_ppx a bit I actually thought of extracting the withStyles ppx into its own repo that should be installed and compiled with esy. I’m experimenting with another project I’m working on right now, if that wies at all I’ll give it a go for this one!

Confirmation by any Linux users of the current PR would be great though :)

**Comment by studious** [comment]
I'm having trouble inside docker with ppx_WithStyles. 

It runs but complains about a missing ")" in quite a few files. It works fine if I install everything from my mac and run it from there, but if I yarn install it from inside docker (node-alpine) and run it I get the following error against many files. Even more odd is that it is not against all files.

```
FAILED: client/sx/word_temple/src/Layout.mlast 
/app/node_modules/bs-platform/lib/bsc.exe -pp "/app/node_modules/bs-platform/lib/refmt.exe --print binary" -ppx '/app/node_modules/bs-platform/lib/reactjs_jsx_ppx_2.exe'  -ppx /app/node_modules/graphql_ppx/ppx -ppx /app/./node_modules/@jsiebern/bs-material-ui/ppx_withStyles -w -30-40+6+7+27+32..39+44+45+101 -bs-suffix -nostdlib -I '/app/node_modules/bs-platform/lib/ocaml' -no-alias-deps -color always -c -o client/sx/word_temple/src/Layout.mlast -bs-syntax-only -bs-binary-ast -impl /app/client/sx/word_temple/src/Layout.re
/app/./node_modules/@jsiebern/bs-material-ui/ppx_withStyles: 3: /app/./node_modules/@jsiebern/bs-material-ui/ppx_withStyles: Syntax error: word unexpected (expecting ")")
File "/app/client/sx/word_temple/src/Layout.re", line 1:
Error: Error while running external preprocessor
Command line: /app/./node_modules/@jsiebern/bs-material-ui/ppx_withStyles '/tmp/camlppx7efdf6' '/tmp/camlppx9974e8'
```

**Comment by jsiebern** [comment]
@studious could you give @liamcurry s PR #14 a try please?

**Comment by liamcurry** [comment]
FYI with that PR you will need to change `ppx_withStyles` to `ppx_withStyles_linux` in your `bsconfig.json` file.

**Comment by jsiebern** [comment]
Can you guys please try the tag `@jsiebern/bs-material-ui@next` and lmk if the postinstall script works okay? I just tested and it seems to be fine. Also note that the update requires `bs-platform@^4.0.0`!

**Comment by liamcurry** [comment]
@jsiebern Yep the postinstall script is working!

**Comment by studious** [comment]
https://github.com/jsiebern/bs-material-ui/blob/master/copyPlatformBinaryInPlace.js#L38

```if (!fs.existsSync('ppx')) {```

Should be

```if (!fs.existsSync('ppx_withStyles')) {```

**Comment by jsiebern** [comment]
@studious Thanks for pointing that one out, I was in a rush this weekend! I'll get that fixed and publish the new version!

**Comment by jsiebern** [comment]
Closing this issue for now as it was reported working. Please test the beta (`@latest`) and feel free to re-open this issue. Otherwise I'll publish the new version regularly soon.
