### ISSUE TITLE
Can't get any of the examples to compile

### ISSUE THREAD

**Issue by KasperJanssens** [jsiebern/bs-material-ui#71]
I must be doing something terribly stupid but I can't seem to get any of the examples to work. I am rather new to ReasonML.
I tried to make a minimal example 
```
[@react.component]
let make = () => {
  <div>
    <MaterialUi.List>
    </MaterialUi.List>
  </div>;
};
```

When I try to compile it it tell me this:
 

>   4 ┆ 
>   5 ┆ <div>
>   6 ┆   <MaterialUi.List>
>   7 ┆   </MaterialUi.List>
>   8 ┆ </div>;
>    This has type:
>     'a =>
>     ReasonReact.component(ReasonReact.stateless, ReasonReact.noRetainedProps,
>                            ReasonReact.actionless)
>   But somewhere wanted:
>     React.component('a) (defined as 'a => React.element)
>   The incompatible parts:
>     ReasonReact.component(ReasonReact.stateless, ReasonReact.noRetainedProps,
>                            ReasonReact.actionless)
>       (defined as
>       ReasonReact.componentSpec(ReasonReact.stateless, ReasonReact.stateless,
>                                  ReasonReact.noRetainedProps,
>                                  ReasonReact.noRetainedProps,
>                                  ReasonReact.actionless))
>     vs
>     React.element

So I am a bit unsure what this says because I suspect there are some type aliases at work here, but it seems to suggest I need to pass in a function instead of a value somewhere. I can't really make it out though.

I installed the @jsiebern/bs-material-ui version 1.1.1, the @material-ui/core version 3.9.2, reason-react 0.7.0 and bs-platform 6.2.1.  Is there some clash between those versions or so?

**Comment by infodevart** [comment]
Exactly the same error here. I'm discovering Reasonml and I wanna give ReasonReact a shot.

**Comment by jsiebern** [comment]
I'm sorry guys, I desperately need to publish the hooks bindings onto the master branch.

For now, just run
`yarn add @jsiebern/bs-material-ui@hooks`

**Comment by infodevart** [comment]
@jsiebern wow that was a really fast answer. I just tried that and everything compiles fine, but if I use a MaterialUi component the page becomes blank and I got this error in the browser console 
/src/Dashboard/Dashboard.bs/__mod/@material-ui/core 404 not found. 
Still really thanks for the good work here.

**Comment by KasperJanssens** [comment]
Okay this seems to work locally on my machine, but I cannot find a version for this and cannot add it to my package.json it seems. It always complains that the version I try to install is not present. Bit annoying for my CI ;-)

**Comment by jsiebern** [comment]
@KasperJanssens 
The current version to use would be `1.1.0-hooks.14` instead of `1.1.1`!
So the command `yarn add @jsiebern/bs-material-ui@1.1.0-hooks.14` should install the right one.

@infodevart 
You need to install MaterialUI separately, it's listed as a peer dependency only.
`yarn add @material-ui/core @material-ui/styles`
That should do it 👍

**Comment by KasperJanssens** [comment]
yeah so I am using npm and this is my dependenies list :
  "dependencies": {
    "@jsiebern/bs-material-ui": "^1.1.0-hooks.14",
    "@material-ui/core": "^3.9.2",
    "bs-webapi": "^0.15.6"
  },

I need to specifically do npm install --save @jsiebern/bs-material-ui@hooks on top of that if not I get an issue during run time 'TypeError: "u.makeProps is not a function"'.
If I then do this : npm install --save @jsiebern/bs-material-ui@hooks it seems to run. No idea why. Some transitive dependency coming in? Also I keep on getting the warning
'├── @jsiebern/bs-material-ui@1.1.0-hooks.14 
└── UNMET PEER DEPENDENCY @material-ui/core@3.9.4
'
Even though material ui is installed. Any ideas or an npm specific issue you think?

**Comment by infodevart** [comment]
@jsiebern I just did a new project and  installed the dependencies but now I got the problem with the Popper

http://localhost:8000/moduleserve/mod/node_modules/@material-ui/core/Popper/Popper/__mod/popper 404 (Not Found)

**Comment by jsiebern** [comment]
@KasperJanssens Material UI should be version v4.x, that's what the latest hooks version uses.

@infodevart What are you using to serve it? Is that an HTTP/2 server? Never experimented with it before to be honest.

**Comment by JanKaul** [comment]
First of all, thanks for the amazing work. It is such a helpful library.

I also get 
`Error: http://localhost:8000/moduleserve/mod/node_modules/@material-ui/core/Popper/Popper/__mod/popper: Not Found`. 

I'm quite new to this, so this could be not what you mean, but I guess it is served with moduleserve [https://github.com/marijnh/moduleserve](https://github.com/marijnh/moduleserve) as provided by the bucklescript react-hooks template [https://github.com/BuckleScript/bucklescript/tree/master/jscomp/bsb/templates/react-hooks](https://github.com/BuckleScript/bucklescript/tree/master/jscomp/bsb/templates/react-hooks).

I think it fails in `node_modules/@material-ui/core/Popper/Popper:18` which looks like this

`var _popper = _interopRequireDefault(require("popper.js"));`

So it seems like something related to the popper.js module.
