### ISSUE TITLE
Arrow prop doesn't exist for tooltip.

### ISSUE THREAD

**Issue by kd4001** [jsiebern/bs-material-ui#73]
Arrow prop doesn't exist as a prop for tooltip. Can someone please add the prop. Implementation exists in material-ui binding. Or some other way to implement this ?

<img width="1439" alt="Screenshot 2019-12-16 at 3 33 50 PM" src="https://user-images.githubusercontent.com/57889116/70898010-d0593580-2019-11ea-8c3c-9cb4cfef497e.png">

**Comment by jsiebern** [comment]
Hi, the bindings always lag a little behind the main version. I'll see if I can get an update out quickly. Thanks for the notice!

**Comment by kd4001** [comment]
I guess it's not in version v4.6.1. Version upgrade needs to be done for @material-ui/core v4.8.0.
Is this update anytime soon?

**Comment by jsiebern** [comment]
Yeah, for sure, hope I can get this done today but can't promise anything. Soon anyway 👍

**Comment by kd4001** [comment]
Hey, any update on this issue?

**Comment by jsiebern** [comment]
Got the package updated, new release coming today. Thanks for reporting :)

**Comment by kd4001** [comment]
Thanks for the resolving the issue.
