### ISSUE TITLE
Cannot pass id-property to all components

### ISSUE THREAD

**Issue by KasperJanssens** [jsiebern/bs-material-ui#75]
I noticed that not all components can have the id property passed to them. For instance, TextField can, but List can not, it is not available in its properties. Having the id attribute in the dom tree is really pracitcal when trying to run selenium tests on it I find. 

Is there a reason why this attribute is not available? I do not think my use case is so exotic, so that's why I am not sure whether I might be missing something here, cause there might be a good reason for not having this id attribute in there.

**Comment by jsiebern** [comment]
@KasperJanssens The `id` Prop also comes from auto-generation (so basically wether it's documented by MUI or not). Probably no harm in adding it everywhere but I really don't want to put "general" attributes everywhere. That would just dilute the autocompletion advantages in my opinion.

**Comment by KasperJanssens** [comment]
I understand. Not having the id-property  is something that is very annoying while trying to assert components on screen. Striking a balance with the usefulness of autocompletion and the usefulness of the library itself is of course very important. Not having this id property is a bit painful, css queries are not very readable and are rather brittle.

**Comment by jsiebern** [comment]
For testing I usually create a higher order component that gets compiled away in production mode. Something like:
``` 
<TestRef id="button-login">
    <Button .... />
</TestRef>
```
Output in test/dev node env is then:
`<span id="button-login"> <button ... /> </span>` or whatever wrapping element makes sense.

In production: `<button ... />`. 

I made one with cloning the element in test env and applying the id as well at one point in time. I believe that's a better approach than putting id on everything for the bindings.

**Comment by KasperJanssens** [comment]
Interesting, by production mode do you mean putting the NODE_ENV variable to production? Or is this something reasonml-specific? This feels like quite some overhead for something as simple as an id prop though, to be honest (mainly for the sheer amount of those TestRefs I would possibly have), but I understand your point of view.

**Comment by jsiebern** [comment]
I have added the `id` prop for all components to the upcoming release.
