### ISSUE TITLE
Support x64 linux

### ISSUE THREAD

**Issue by arsdragonfly** [jsiebern/bs-material-ui#76]
```
error /home/arsdragonfly/reasonml/bs-material-ui/node_modules/@jsiebern/bs-material-ui-ppx: Command failed.
Exit code: 1
Command: node ./copyPlatformBinaryInPlace.js
Arguments: 
Directory: /home/arsdragonfly/reasonml/bs-material-ui/node_modules/@jsiebern/bs-material-ui-ppx
Output:
bs_material_ui_ppx does not support this platform :(

bs_material_ui_ppx comes prepacked as built binaries to avoid large
dependencies at build-time.

If you want bs_material_ui_ppx to support this platform natively,
```

**Comment by jsiebern** [comment]
Could you tell me the exact OS you are running? Gotta see if I can get that tested somehow. Thanks!

**Comment by leeor** [comment]
I ran into this issue trying to build in a docker container based on the official node image - which is based on Debian.

I'm currently using a workaround script that builds the ppx before it builds my app. It costs me an extra 5-6 minutes per build.

**Comment by unodgs** [comment]
I also have the same problem. I use jenkins in docker: `Linux 19ea5e7c64ec 4.15.0 #1 SMP Mon Dec 9 19:36:21 MSK 2019 x86_64 GNU/Linux`

**Comment by unodgs** [comment]
Hmm it looks like `copyPlatformBinaryInPlace.js` doesn't correctly recognise alpine linux as linux binary `bs_material_ui_ppx-linux-x64.exe` works fine

**Comment by jsiebern** [comment]
@leeor Which docker image exactly? I just tried it with a few of the node ones and could not reproduce it. Also used other linux alpine distributions, never got the error :-( 

@unodgs Also just tried the `jenkins` (and `jenkins:alpine`). Your error I could actually reproduce. I have no idea why, but the copy process for ppx6 seems to be flawed (see the size):
```
-rwxr-xr-x 1 root root 20154008 Apr 27 17:54 ppx
-rwxr-xr-x 1 root root 20154008 Apr 27 17:54 ppx.exe
-rwxr-xr-x 1 root root 13762508 Apr 18 21:18 ppx6
-rwxr-xr-x 1 root root 20154008 Apr 27 17:54 ppx6.exe
```

Just change your ppx-flags string to `@jsiebern/bs-material-ui-ppx/ppx` and it should work fine. The ocaml versions are unified anyway. If necessary, update your ppx npm version to `1.1.0-test.2
` or even `1.1.0-zero.1` if you're feeling adventurous 😉 

I will strip all these bin files soon anyway, as they don't make sense anymore.

**Comment by jsiebern** [comment]
Note: If you choose to try `1.1.0-zero.1`, you need to change the style format from
```reason
[%mui.withStyles "Styles"{ ... });
```
to
```reason
module Styles = [%makeStyles {...}];
```

**Comment by leeor** [comment]
> @leeor Which docker image exactly? I just tried it with a few of the node ones and could not reproduce it. Also used other linux alpine distributions, never got the error :-(

Just tested again, using `node:12` for the base image. I don't get the OP error (though I definitely used to a few month ago) but I do get this:
```
FAILED: __tests__/canned/Data1.reast 
/usr/src/app/node_modules/bs-platform/lib/bsc.exe  -w -30-40+6+7+27+32..39+44+45+101+A-42-48 -warn-error +A-3-44-102 -color always -bs-jsx 3 -ppx '/usr/src/app/node_modules/@baransu/graphql_ppx_re/ppx6 -apollo-mode -lean-parse' -ppx /usr/src/app/node_modules/bs-let/ppx -ppx /usr/src/app/node_modules/@jsiebern/bs-material-ui-ppx/ppx6 -ppx /usr/src/app/node_modules/bs-log/ppx  -o __tests__/canned/Data1.reast -bs-syntax-only -bs-binary-ast /usr/src/app/packages/frontend/__tests__/canned/Data1.re
sh: 1: /usr/src/app/node_modules/@jsiebern/bs-material-ui-ppx/ppx6: Exec format error

```

**Comment by jsiebern** [comment]
That's the other issue mentioned here, please try this:
> Just change your ppx-flags string to @jsiebern/bs-material-ui-ppx/ppx and it should work fine.

**Comment by leeor** [comment]
@jsiebern, `1.1.0-test.2` works well, thanks.

Is there somewhere a list of the changes in each of those ppx versions?

**Comment by jsiebern** [comment]
That's great news, I'll mark this as complete for now then as I suspect that @arsdragonfly 's problems are gone now as well. 

Unfortunately there is no changelog for the PPX, I should rectify that. Hit me up on Discord if you have any questions (Jonathan#2836). There is a new version in the works that will bring a lot of breaking changes but greatly improves code generation & with it performance. Check out the `@zero` versions of each package if you're interested.
