### ISSUE TITLE
Prop names: change leading underscore to trailing underscore

### ISSUE THREAD

**Issue by cknitt** [jsiebern/bs-material-ui#8]
In 0.4.2, reason-react moved from leading underscores (`_open`, `_type`, ...) to trailing underscores  (`open_`, `type_`, ...), see https://github.com/reasonml/reason-react/blob/master/HISTORY.md.

I think the material-ui bindings should follow suit. Trailing underscores just make more sense, as a leading underscore usually means "unused" in Reason/OCaml.

**Comment by jsiebern** [comment]
Agreed, I had it like that before until it was mentioned that the current best practice was to make them leading. Oh well 😄

**Comment by jsiebern** [comment]
Closing as it should be fixed in `v0.3.1`.
