### ISSUE TITLE
SSR Support : ServerStyleSheet bindings

### ISSUE THREAD

**Issue by hpierre74** [jsiebern/bs-material-ui#80]
Hi, thanks for the amazing job you did so far !

Do you plan to ship bindings for ServerStyleSheet any time soon ?

If not how would you think such bindings would look, I have hard times finding how to handle classes which implements methods ?

**Comment by jsiebern** [comment]
I have added this to the upcoming version. You can find the example code here:
https://github.com/jsiebern/bs-material-ui/blob/393c80fbdfae5ae83bdd6f749c9f8f10e19664e9/public/bs-material-ui/examples/ExampleServerStyleSheets.re#L17-L23
