### ISSUE TITLE
TextField should not allow children.

### ISSUE THREAD

**Issue by erlandsona** [jsiebern/bs-material-ui#81]
It seems obvious now but the fact that TextField renders to a raw `<input />` <- and inputs clobber their children, shouldn't MaterialUi not allow the children prop to be passed?
This code was silently failing.
```
MaterialUi.(
  <TextField>
    <Popover>
      <MenuList><ListItem><ListItemText></ListItemText></ListItem></MenuList>
    </Popover>
  </TextField>
);
```
 And it took a day and half to realize that TextField and Popover needed to be siblings for the code to work. EG:
```
MaterialUi.(
  <TextField />
  <Popover>
    <MenuList><ListItem><ListItemText></ListItemText></ListItem></MenuList>
  </Popover>
);
```

If we remove [~children](https://github.com/jsiebern/bs-material-ui/blob/c53e2e8598745b77e6edafa43bb01031098a2bb9/public/bs-material-ui/src/MaterialUi_TextField.re#L51) from MaterialUi_TextField.make signature this should throw a compile error which would prevent misuse of this component for future users.

**Comment by jsiebern** [comment]
I have looked into this extensively and tried to determine when to be able to ignore these kinds of props automatically. Unfortunately the Docs of Mui don't make good distinctions. `TextField` inherits from `FormControl`, so there's no good way to keep these out unfortunately.  Shouldn't be an issue for most anyway.

**Comment by erlandsona** [comment]
Why not look at the underlying HTML component? Sure TextField inherits from form control but ultimately it turns into a bunch of docs decorating an input element which will just clobber any children passed in.

Am I missing something?

**Comment by jsiebern** [comment]
I'll say this: It's unfortunately not possible without blowing the maintenance cost of these bindings completely out of proportion, sorry.
