### ISSUE TITLE
Binding for the "useMediaQuery" hook

### ISSUE THREAD

**Issue by Yakimych** [jsiebern/bs-material-ui#84]
Seems to be enough with the following for this binding:
```
[@bs.module "@material-ui/core"]
external useMediaQuery: string => bool = "useMediaQuery";
```
I was thinking adding this one and a binding for the Box component, but ran into problems when trying to build locally - is there a contributors guide one could follow otherwise?

**Comment by jsiebern** [comment]
Hi, thanks for that code, I'll be sure to include it in the upcoming version. Unfortunately building the project is not exactly straight forward. Some code even still relies on my local paths. I realize it's a no-go but I have hardly time to maintain the project as it is, let alone refactor it for contributors unfortunately.

It will be available at `MaterialUi.Core`, probably like so:
```ml
let theme = MaterialUi.Core.useTheme();
let matches =
  MaterialUi.Core.(useMediaQuery(theme->Breakpoint.get(`up(`sm))));
let matchesAsString = MaterialUi.Core.useMediaQueryString("(min-width:600px)");
```
