### ISSUE TITLE
PPX not building on OSX bs-platform 7.0.2-dev.1, Linux CI bs-platform 7.1.1

### ISSUE THREAD

**Issue by erlandsona** [jsiebern/bs-material-ui#85]
Ran this...
`yarn add --dev @jsiebern/bs-material-ui-ppx`

Added "@jsiebern/bs-material-ui-ppx/ppx6", to bsconfig.json
And...
```
$ yarn bs:dev
yarn run v1.21.1
$ bsb -make-world -w

FeatureA.re
Fatal error: exception File "/Users/aerlandson/code/client/src/features/featureA/FeatureA.re", line 8, characters 4-7: inline records are not supported before OCaml 4.03

  We've found a bug for you!
    /Users/aerlandson/code/client/src/features/featureA/FeatureA.re

      Error while running external preprocessor
      Command line: /Users/aerlandson/code/client/node_modules/@jsiebern/bs-material-ui-ppx/ppx6
```
@aantron in Discord suggested...
> what this error means is that ppx6, even though it is reading ocaml 4.06 ASTs, is internally converting them to ocaml 4.02 ASTs
> this https://github.com/jsiebern/bs-material-ui/blob/master/public/bs-material-ui-ppx/src/dune#L7 https://github.com/jsiebern/bs-material-ui/blob/master/public/bs-material-ui-ppx/src/Replace.re#L1 https://github.com/jsiebern/bs-material-ui/blob/master/public/bs-material-ui-ppx/src/Mapper.re#L1 etc needs to be patched to replace 402 with 406
> you might as well patch all the way to 4.09 right now, if the project's build allows to pull in 4.09
scratch that, 4.09 ASTs will be available assuming a high enough version of OMP, https://github.com/jsiebern/bs-material-ui/blob/master/public/bs-material-ui-ppx/esy.json#L6, look in the OMP changelog

I gave a shot at building my fork of the repo locally this morning but started falling down the rabbit hole of upgrading the code-gen lib from ocaml-migrate-parsetree from 4.02 to 4.06 syntax... after I got the right version of dune building for my OS...

```
# Unformatted Error Output:
# File "src/Generate.re", line 7, characters 4-241:
# Error: This variant expression is expected to have type
#          Migrate_parsetree__Ast_406.Asttypes.rec_flag
#        The constructor :: does not belong to type Migrate_parsetree__Ast_406.Asttypes.rec_flag


 ERROR  src/Generate.re:7:4-15:6

  4 ┆
  5 ┆ let genTypeFromType = (name: string, typeName: string) =>
  6 ┆   Ast_helper.Str.type_([
  7 ┆     Ast_helper.Type.mk(
  8 ┆       ~manifest={
  9 ┆         ptyp_desc:
 10 ┆           Ptyp_constr(Location.mknoloc(Longident.Lident(typeName)), []),
```

**Comment by aantron** [comment]
FYI the the internal AST should be upgraded to the latest one available from OMP, no matter what version of the compiler the PPX is meant to work with, because this will maximize the forward-compatibility of each subsequent bs-material-ui-ppx release with respect to this kind of error. At the moment, that would be 4.09 or 4.10.

**Comment by brad-decker** [comment]
For some reason everything works locally for me, but when I attempt to deploy to zeit's now, it shows a similar error as above. Is this the same issue? 

```
FAILED: src/hooks/UseLQIP.reast
2020-02-24T15:41:15.163Z  /zeit/7895b018/node_modules/bs-platform/lib/bsc.exe   -color always -bs-jsx 3 -ppx /zeit/7895b018/node_modules/@jsiebern/bs-material-ui-ppx/ppx6 -bs-super-errors -o src/hooks/UseLQIP.reast -bs-syntax-only -bs-binary-ast /zeit/7895b018/src/hooks/UseLQIP.re
2020-02-24T15:41:15.163Z  sh: /zeit/7895b018/node_modules/@jsiebern/bs-material-ui-ppx/ppx6: cannot execute binary file
2020-02-24T15:41:15.163Z
2020-02-24T15:41:15.163Z    We've found a bug for you!
2020-02-24T15:41:15.164Z    /zeit/7895b018/src/hooks/UseLQIP.re
2020-02-24T15:41:15.164Z
2020-02-24T15:41:15.164Z    Error while running external preprocessor
2020-02-24T15:41:15.164Z  Command line: /zeit/7895b018/node_modules/@jsiebern/bs-material-ui-ppx/ppx6 '/tmp/camlppx981fd8' '/tmp/camlppx02a9a4'
```

**Comment by brad-decker** [comment]
For now i've created the following API for creating styles with material-ui without the ppx:

```
type classes = {
  header: string,
  avatar: string,
  grid: string,
  card: string,
};
let useStyles =
  Styles.(
    createStyles(
      WithTheme(
        theme =>
          {
            header:
              make([
                backgroundColor(
                  getPalette(~mode=`dark, ~color=`primary, ~theme),
                ),
              ]),
            avatar:
              make([
                backgroundColor(getTextPalette(~variation=`primary, ~theme)),
              ]),
            grid: make([selector("& > *", [flexGrow(1.)])]),
            card: make([height(`percent(100.))]),
          },
      ),
    )
  );

[@react.component]
let make = () => {
  let classes = useStyles(.);
```
The overhead of creating the record is "not great, not terrible". I tried ejecting from material-ui altogether for these extra style additions, bs-css can do it out of the box but with my app i'm using SSR and trying to figure out how to get that all working was a pita.

My custom Styles.re module:
```
include Css;
external convertJsonToString: Js.Json.t => string = "%identity";
[@bs.module "@material-ui/core/styles"]
external makeStyles: 'a => (. unit) => 'a = "makeStyles";
[@bs.module "@material-ui/core/styles"]
external makeStylesWithTheme: (MaterialUi_Theme.t => 'a) => (. unit) => 'a =
  "makeStyles";
let make = (styles: list(Css.rule)) =>
  styles->Css.toJson->convertJsonToString;
type styleType('a) =
  | Static('a)
  | WithTheme(MaterialUi_Theme.t => 'a);

let createStyles = (styles: styleType('a)) => {
  switch (styles) {
  | Static(rules) => makeStyles(rules)
  | WithTheme(rules) => makeStylesWithTheme(rules)
  };
};

module WithStyle = {
  [@react.component]
  let make = (~children, ~styles) => {
    let hook = createStyles(styles);
    let classes = hook(.);
    children(classes);
  };
};
```

**Comment by erlandsona** [comment]
I got this working locally with bs-platform v7.1.1 after bs-abstract merged the PR that enabled me to make the upgrade.

Now I've got this error happening in CI...
```
client/node_modules/@jsiebern/bs-material-ui-ppx/ppx6: 1: /root/client/node_modules/@jsiebern/bs-material-ui-ppx/ppx6: Syntax error: word unexpected (expecting ")")
13:32:56  
13:32:56    We've found a bug for you!
13:32:56    /root/client/src/EpicT.re
13:32:56    
13:32:56    Error while running external preprocessor
```
EpicT.re doesn't have any references to `[%mui.withStyles]` in it so I'm inclined to think it's an issue with the ppx on Linux?

**Comment by timerg** [comment]
I got this error, too.
The complier works fine on local but fail when run CI in linux environment.
```
"@jsiebern/bs-material-ui-ppx": "^1.0.6",
"bs-platform": "^7.2.2",
```

```
sh: 1: /.../node_modules/@jsiebern/bs-material-ui-ppx/ppx6: Exec format error

  We've found a bug for you!
  /.../src/__tests__/firstTesting.re
  
  Error while running external preprocessor
Command line: /.../node_modules/@jsiebern/bs-material-ui-ppx/ppx6 '/tmp/camlppxc2eddc' '/tmp/camlppx927391'
```
firstTesting.re doesn't have any `[%mui]` flag.

But after changed CI environment from Linux to macOSX, the error disappeared. I've also tried other ppx tools and all work fine. Thus it should be an issue with ppx on Linux.
