### ISSUE TITLE
Binding for labs/Autocomplete plez!!! :pray:

### ISSUE THREAD

**Issue by erlandsona** [jsiebern/bs-material-ui#88]
Would love to have this... currently implementing my own less good version of this with TextField and Menu... except it doesn't autocomplete 🤷‍♂ .

**Comment by jsiebern** [comment]
All lab components are now available [here](https://www.npmjs.com/package/@jsiebern/bs-material-ui-lab).

```
yarn add @jsiebern/bs-material-ui-lab
```

These are untested yet, so we might need to iterate a bit, before everything works.
