### ISSUE TITLE
TableCell: wrong type for binding to sortDirection

### ISSUE THREAD

**Issue by mikaello** [jsiebern/bs-material-ui#91]
`sortDirection` in `TableCell` has [this binding](https://github.com/jsiebern/bs-material-ui/blob/master/public/bs-material-ui/src/MaterialUi_TableCell.re#L20-L25): 
```reason
[@bs.deriving jsConverter]
type sortDirection = [
  | [@bs.as "asc"] `Asc
  | [@bs.as "desc"] `Desc
  | [@bs.as "false"] `False
];
```

But the [expected type is ` 'asc' | 'desc' | false`](https://material-ui.com/api/table-cell/#props). The error is `false`, that is sent as a string from this lib, but is expected as a boolean, from console:
```
Warning: Failed prop type: Invalid prop `sortDirection` of value `false` supplied to `ForwardRef(TableCell)`, expected one of ["asc","desc",false].
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
    ...
    ...
```

Is it possible to convert `` `False`` to a boolean, or remove `` `False`` and instead make it possible to provide `None` and convert that to `false`? I do not have much experience with ReasonML, so I don't know what is the most idiomatic way to type this.

(related: I tried to use the same variable to control sort direction in `TableCell` and [`TableSortLabel`](https://github.com/jsiebern/bs-material-ui/blob/master/public/bs-material-ui/src/MaterialUi_TableSortLabel.re#L2), but that is not possible since this type has the `` `False`` option that does not exist in `TableSortLabel.direction`)

**Comment by jsiebern** [comment]
This will be fixed in the upcoming version
