### ISSUE TITLE
Incorrect Type: Typography constructor's ~fontSize should be number, not string.

### ISSUE THREAD

**Issue by Phylodome** [jsiebern/bs-material-ui#95]
It appears that though the `make` function created by `[@bs.deriving abstract]` for `Typography` records only accepts `~fontSize:string`, the MaterialUI library requires that this property be a number, going so far as to enforce a `typeof` check:

**`material-ui` library:**
![Screen Shot 2020-04-01 at 3 03 31 PM](https://user-images.githubusercontent.com/241837/78191749-814dd980-742b-11ea-84bf-42ac391e2a20.png)

**`bs-material-ui` api:**
![Screen Shot 2020-04-01 at 3 17 25 PM](https://user-images.githubusercontent.com/241837/78191924-e99cbb00-742b-11ea-99d7-70d80380d800.png)

**Comment by jsiebern** [comment]
Should be fixed in the upcoming version.
